const express = require('express');
const swaggerUi = require('swagger-ui-express');
const YAML = require('yamljs'); // If using YAML format
// const swaggerDocument = require('./swagger.json'); // If using JSON format

const swaggerDocument = YAML.load('./swagger.yaml'); // Load Swagger/OpenAPI spec

const app = express();

// Serve Swagger UI
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

// Your API routes and other middleware
// app.use('/products', productsRouter);

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
